name: glamcode
description: Glamcode - Luxury Salon at Home
publish_to: "none"
# version: 1.3.0
#change the minimum app version in Update screen also
version: 2.0.4
Controlsleep time:
environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  youtube_player_iframe: ^3.1.0
  carousel_slider: ^4.2.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  cached_network_image: ^3.2.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  meta: ^1.8.0
  pinput: ^2.2.19
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter_widget_from_html: ^0.9.0+1
  google_maps_flutter: ^2.5.0
  # google_maps_place_picker_mb: ^3.0.1
  geocoding: ^2.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  syncfusion_flutter_calendar: ^20.4.38
  intl: ^0.18.0
  razorpay_flutter: ^1.3.0
  fluttertoast: ^8.1.2
  url_launcher:
  swipe_image_gallery: ^0.8.0
  video_player: ^2.4.10
  firebase_core: ^2.15.0
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.5.0
  firebase_performance: ^0.9.0+9
  firebase_crashlytics: ^3.0.9
  flutter_local_notifications: ^12.0.0
  http: ^0.13.5
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^1.1.6
  share_plus:
  scratcher: ^2.3.0
  confetti: ^0.7.0
  geolocator: ^10.1.0
  new_version:
    path: "clone_libs/new_version"
  launch_review: ^3.0.1
  package_info_plus: ^4.0.2
  firebase_remote_config: ^4.1.0
  flutter_app_version_checker:
    path: "clone_libs/app_version_checker"
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  open_street_map_search_and_pick: ^0.1.0
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.9.2
  uuid: ^3.0.7
  location_geocoder: ^1.0.5
  modal_progress_hud_nsn: ^0.4.0
  flutter_slidable: ^3.0.0
  swipeable_button_view: ^0.0.2
  shimmer: ^3.0.0
  facebook_app_events: ^0.19.0
  upgrader: ^8.4.0
  package_info: ^2.0.2
  # package_info_plus: ^4.2.0
  version: ^3.0.2

  # google_maps_place_picker_mb: ^3.0.2
  # flutter_html: ^0.8.2

# location:
#     git:
#       url: https://github.com/781flyingdutchman/flutterlocation.git
#       ref: 'V4'
#       path: packages/location

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: "ic_launcher"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
